version: "3.8"
services:
  prometheus:
    image: prom/prometheus:v2.22.1
    volumes: 
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always
  
  grafana:
    image: grafana/grafana:7.3.1
    ports:
      - 43000:3000
    environment:
      GF_SECURITY_ADMIN_PASSWORD: {password}

