global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  
  - job_name: '25.63'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    static_configs:
      - targets: ['140.134.25.63:11000']
      
      
  - job_name: '25.64'

    scrape_interval: 5s

    static_configs:
      - targets: ['140.134.25.64:11000']
  
  - job_name: '25.65'

    scrape_interval: 5s

    static_configs:
      - targets: ['140.134.25.65:11000']
      
      
  - job_name: '26.66'

    scrape_interval: 5s

    static_configs:
      - targets: ['140.134.26.66:11000']
      
      
  - job_name: '26.71'
  
    scrape_interval: 5s

    static_configs:
      - targets: ['140.134.26.71:11000']
  
      
  - job_name: '26.72'
  
    scrape_interval: 5s

    static_configs:
      - targets: ['140.134.26.72:11000']
      
      
  